package com.kilari.agentic.tools;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Set;
import java.util.Comparator;
import java.util.stream.Stream;

/**
 * Creates isolated workspaces for workflow runs.
 *
 * <p>Each run gets its own directory, so a failed or abandoned run cannot leave
 * artifacts where a later run would pick them up and mistake them for its own
 * work. The build wrapper is installed by the platform rather than generated by
 * an agent — {@link PathPolicy} refuses to let a patch write these paths, which
 * would otherwise be the easiest route from "generate a file" to "execute
 * arbitrary code during validation".
 */
public class WorkspaceFactory {

    private static final Logger log = LoggerFactory.getLogger(WorkspaceFactory.class);

    private static final List<String> WRAPPER_FILES = List.of(
            "gradlew",
            "gradle/wrapper/gradle-wrapper.jar",
            "gradle/wrapper/gradle-wrapper.properties");

    private final Path workspacesRoot;
    private final Path wrapperSource;

    public WorkspaceFactory(Path workspacesRoot, Path wrapperSource) {
        this.workspacesRoot = workspacesRoot.toAbsolutePath().normalize();
        this.wrapperSource = wrapperSource.toAbsolutePath().normalize();
    }

    /**
     * Creates an empty workspace with a working build wrapper.
     *
     * @param workflowId used as the directory name so a workspace can be traced
     *                   back to the run that produced it
     */
    public Path create(String workflowId) {
        Path workspace = workspacesRoot.resolve(workflowId);
        try {
            Files.createDirectories(workspace);
            installWrapper(workspace);
        } catch (IOException e) {
            throw new UncheckedIOException("could not create workspace " + workspace, e);
        }
        log.info("Created workspace {}", workspace);
        return workspace;
    }

    private void installWrapper(Path workspace) throws IOException {
        for (String relative : WRAPPER_FILES) {
            Path source = wrapperSource.resolve(relative);
            if (!Files.exists(source)) {
                throw new IOException("build wrapper file missing from platform install: " + source);
            }
            Path target = workspace.resolve(relative);
            Files.createDirectories(target.getParent());
            Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
        }

        Path gradlew = workspace.resolve("gradlew");
        // Copy does not preserve the executable bit on every filesystem, and a
        // wrapper that cannot be executed fails validation in a way that looks
        // like a code defect rather than a setup problem.
        gradlew.toFile().setExecutable(true, false);
    }

    /** Removes a workspace and everything under it. */
    public void destroy(Path workspace) {
        Path normalized = workspace.toAbsolutePath().normalize();
        if (!normalized.startsWith(workspacesRoot)) {
            throw new IllegalArgumentException(
                    "refusing to delete a path outside the workspaces root: " + normalized);
        }
        if (!Files.exists(normalized)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(normalized)) {
            paths.sorted(Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.delete(path);
                } catch (IOException e) {
                    log.warn("Could not delete {}: {}", path, e.getMessage());
                }
            });
        } catch (IOException e) {
            throw new UncheckedIOException("failed to destroy workspace " + normalized, e);
        }
    }

    public Path workspacesRoot() {
        return workspacesRoot;
    }

    /** Paths the platform installs, which agents are not permitted to author. */
    public static Set<String> wrapperPaths() {
        return Set.copyOf(WRAPPER_FILES);
    }
}
